# coding: utf-8

"""
    lunaform

    This is a RESTful server for managing Terraform plan and apply jobs and the auditing of actions to approve those apply jobs. The inspiration for this project is the AWS CloudFormation API's. The intention is to implement a locking mechanism not only for the terraform state, but for the plan and apply of terraform modules. Once a `module` plan starts, it is instantiated as a `stack` within the nomencalture of `lunaform`.   # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    Contact: drew.sonne@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.modules_api import ModulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModulesApi(unittest.TestCase):
    """ModulesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.modules_api.ModulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_module(self):
        """Test case for create_module

        """
        pass

    def test_delete_module(self):
        """Test case for delete_module

        """
        pass

    def test_get_module(self):
        """Test case for get_module

        """
        pass

    def test_list_modules(self):
        """Test case for list_modules

        """
        pass


if __name__ == '__main__':
    unittest.main()
