# coding: utf-8

"""
    lunaform

    This is a RESTful server for managing Terraform plan and apply jobs and the auditing of actions to approve those apply jobs. The inspiration for this project is the AWS CloudFormation API's. The intention is to implement a locking mechanism not only for the terraform state, but for the plan and apply of terraform modules. Once a `module` plan starts, it is instantiated as a `stack` within the nomencalture of `lunaform`.   # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    Contact: drew.sonne@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stacks_api import StacksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStacksApi(unittest.TestCase):
    """StacksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.stacks_api.StacksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deploy_stack(self):
        """Test case for deploy_stack

        """
        pass

    def test_get_stack(self):
        """Test case for get_stack

        """
        pass

    def test_list_deployments(self):
        """Test case for list_deployments

        """
        pass

    def test_list_stacks(self):
        """Test case for list_stacks

        """
        pass

    def test_undeploy_stack(self):
        """Test case for undeploy_stack

        """
        pass


if __name__ == '__main__':
    unittest.main()
