# coding: utf-8

"""
    lunaform

    This is a RESTful server for managing Terraform plan and apply jobs and the auditing of actions to approve those apply jobs. The inspiration for this project is the AWS CloudFormation API's. The intention is to implement a locking mechanism not only for the terraform state, but for the plan and apply of terraform modules. Once a `module` plan starts, it is instantiated as a `stack` within the nomencalture of `lunaform`.   # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    Contact: drew.sonne@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ResourceAuthUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'shortname': 'str',
        'name': 'str',
        'id': 'str',
        'groups': 'list[str]',
        'api_keys': 'list[str]'
    }

    attribute_map = {
        'shortname': 'shortname',
        'name': 'name',
        'id': 'id',
        'groups': 'groups',
        'api_keys': 'api-keys'
    }

    def __init__(self, shortname=None, name=None, id=None, groups=None, api_keys=None):  # noqa: E501
        """ResourceAuthUser - a model defined in Swagger"""  # noqa: E501

        self._shortname = None
        self._name = None
        self._id = None
        self._groups = None
        self._api_keys = None
        self.discriminator = None

        if shortname is not None:
            self.shortname = shortname
        if name is not None:
            self.name = name
        if id is not None:
            self.id = id
        if groups is not None:
            self.groups = groups
        if api_keys is not None:
            self.api_keys = api_keys

    @property
    def shortname(self):
        """Gets the shortname of this ResourceAuthUser.  # noqa: E501


        :return: The shortname of this ResourceAuthUser.  # noqa: E501
        :rtype: str
        """
        return self._shortname

    @shortname.setter
    def shortname(self, shortname):
        """Sets the shortname of this ResourceAuthUser.


        :param shortname: The shortname of this ResourceAuthUser.  # noqa: E501
        :type: str
        """

        self._shortname = shortname

    @property
    def name(self):
        """Gets the name of this ResourceAuthUser.  # noqa: E501


        :return: The name of this ResourceAuthUser.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ResourceAuthUser.


        :param name: The name of this ResourceAuthUser.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this ResourceAuthUser.  # noqa: E501


        :return: The id of this ResourceAuthUser.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ResourceAuthUser.


        :param id: The id of this ResourceAuthUser.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def groups(self):
        """Gets the groups of this ResourceAuthUser.  # noqa: E501


        :return: The groups of this ResourceAuthUser.  # noqa: E501
        :rtype: list[str]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this ResourceAuthUser.


        :param groups: The groups of this ResourceAuthUser.  # noqa: E501
        :type: list[str]
        """

        self._groups = groups

    @property
    def api_keys(self):
        """Gets the api_keys of this ResourceAuthUser.  # noqa: E501


        :return: The api_keys of this ResourceAuthUser.  # noqa: E501
        :rtype: list[str]
        """
        return self._api_keys

    @api_keys.setter
    def api_keys(self, api_keys):
        """Sets the api_keys of this ResourceAuthUser.


        :param api_keys: The api_keys of this ResourceAuthUser.  # noqa: E501
        :type: list[str]
        """

        self._api_keys = api_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceAuthUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
