# coding: utf-8

"""
    lunaform

    This is a RESTful server for managing Terraform plan and apply jobs and the auditing of actions to approve those apply jobs. The inspiration for this project is the AWS CloudFormation API's. The intention is to implement a locking mechanism not only for the terraform state, but for the plan and apply of terraform modules. Once a `module` plan starts, it is instantiated as a `stack` within the nomencalture of `lunaform`.   # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    Contact: drew.sonne@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.hal_rsc_links import HalRscLinks  # noqa: F401,E501
from swagger_client.models.resource_list_tf_provider import ResourceListTfProvider  # noqa: F401,E501


class ResponseListTfProviders(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'links': 'HalRscLinks',
        'embedded': 'ResourceListTfProvider'
    }

    attribute_map = {
        'links': '_links',
        'embedded': '_embedded'
    }

    def __init__(self, links=None, embedded=None):  # noqa: E501
        """ResponseListTfProviders - a model defined in Swagger"""  # noqa: E501

        self._links = None
        self._embedded = None
        self.discriminator = None

        self.links = links
        self.embedded = embedded

    @property
    def links(self):
        """Gets the links of this ResponseListTfProviders.  # noqa: E501


        :return: The links of this ResponseListTfProviders.  # noqa: E501
        :rtype: HalRscLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ResponseListTfProviders.


        :param links: The links of this ResponseListTfProviders.  # noqa: E501
        :type: HalRscLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def embedded(self):
        """Gets the embedded of this ResponseListTfProviders.  # noqa: E501


        :return: The embedded of this ResponseListTfProviders.  # noqa: E501
        :rtype: ResourceListTfProvider
        """
        return self._embedded

    @embedded.setter
    def embedded(self, embedded):
        """Sets the embedded of this ResponseListTfProviders.


        :param embedded: The embedded of this ResponseListTfProviders.  # noqa: E501
        :type: ResourceListTfProvider
        """
        if embedded is None:
            raise ValueError("Invalid value for `embedded`, must not be `None`")  # noqa: E501

        self._embedded = embedded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseListTfProviders):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
